Use forward slash for ZIP file paths
JakBaranowski/gb-tools pull request #1
Opened 2021-09-12 17:07 UTC by Bob-AT

Using backslashes in ZIP file paths causes problems
when extracting on Linux servers

2021-09-13 15:09 UTC, JakBaranowski requested changes
Hey, great catch, and thanks for the pull request. :-) Although could you move the normalisation code to a separate function to avoid doing two things in one function?

2021-09-13 16:46 UTC, Bob-AT commented
I'll refactor at night or tomorrow.

2021-09-24 16:45 UTC, Bob-AT commented
Been busy, almost forgot. I've refactored.

2021-09-25 11:19 UTC, JakBaranowski approved these changes

2021-09-25 11:19 UTC, JakBaranowski commented
No worries, awesome work and thanks for the help.

2021-09-25 11:20 UTC, merged